config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  # get 'static_pages/home'
  # get 'static_pages/help'
  # get 'static_pages/about'
  # get 'static_pages/contact'
  # get '/home', to: 'static_pages#home'
  resources :users
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',to: 'sessions#destroy'

  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { email.downcase! }
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, # is the same as validates{:email, presence:true}
                          format: {with: VALID_EMAIL_REGEX},
                        uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                 BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # user = User.find_by(email: params[:session][:email].downcase)
    # if user && user.authenticate(params[:session][:password])
    #   # Log the user in and redirect to the user's show page.
    #   log_in user
    #   params[:session][:remember_me] == '1' ? remember(user) : forget(user)
    #   redirect_to user

    # FIll_IN
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
      redirect_back_or @user
    else
      # Create an erorr message.
      flash.now[:danger] = 'Kirby says there is a problem with your login.'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about

  end

  def contact

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def new
    @user = User.new
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    # @user = User.find_by(params[:id])
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      log_in @user
      flash[:success] = "Success my friend!"
      redirect_to user_url(@user)
      # redirect_to @user # this work as well #
    else
      render 'new'
    end
  end

  def edit
    # @user = User.find_by(params[:id])
    @user = User.find(params[:id])
  end

  def update
   @user = User.find(params[:id])
   if @user.update_attributes(user_params)
     flash[:success] = "Profile updated"
     redirect_to @user
   else
     render 'edit'
   end
 end

 def destroy
   User.find(params[:id]).destroy
   flash[:success] = "User deleted"
   redirect_to users_url
 end

  private

  def user_params
    params.require(:user).permit(:name , :email, :password,
                                 :password_confirmation)
  end

  # Before filters

  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
        store_location
        flash[:danger] = "Please log in my friend."
        redirect_to login_url
      end
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "KBOY"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Remembers a user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
     @current_user ||= User.find_by(id: user_id)
   elsif (user_id = cookies.signed[:user_id])
     user = User.find_by(id: user_id)
     if user && user.authenticated?(cookies[:remember_token])
       log_in user
       @current_user = user
     end
   end
  end

  # Returns true if the user is logged in , otherwise false.
  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default)
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="https://about.me/k-boy">KIRBY</a>
    &copy; 2016
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://about.me/k-boy">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "KIRBY JAMES", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",  root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                          'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!-- HTML5 Shim for IE browsers -->
   <!--[if lt IE 9]>
     <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
     </script>
   <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>

  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div class="center">
  <div class="alert alert-danger">
                        <!-- first error message option -->
    <!-- Kirby says you have <%= pluralize(@user.errors.count, "error") %>. -->
    Kirby says you need to fill out the following errors.
  </div>
</div>
  <div id="error_explanation">
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="center">
  <div class="wrapper">
    <%= link_to image_tag("kboy.jpg", alt: "KBOY"), 'https://twitter.com/FernandezKboy' %>
  </div>
</div>

<br>

<div class="center">
  <div class="wrapper">
    <%= link_to image_tag("operationcode800.png", alt: "KBOY"), 'https://operationcode.org/' %>
  </div>
</div>

<br>

<div class="center">
  <%= link_to image_tag("opcode.png", alt: "KBOY"), 'https://operationcode.org/' %>  <h2><a href="https://about.me/k-boy">Kirby's</a> brief introduction.</h2>
  <h3>I am part of <a href="https://operationcode.org/">Operation Code</a> founded by an ex-Army Captain.</h3>
  <h3>I usually hangout on <a href="https://github.com/kboygit">Github</a> and <a href="https://slack.com/">Operation Code Slack</a>.</h3>
<iframe src="//giphy.com/embed/asGdT7GTpANb2" width="480" height="320" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/please-construction-patient-asGdT7GTpANb2"></a></p>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="center">
  <div class="wrapper">
    <%= link_to image_tag("kboy.jpg", alt: "KBOY"), 'https://twitter.com/FernandezKboy' %>
  </div>
</div>

<br>

<div class="center">
  <p>
    <a href="https://about.me/k-boy">Contact</a> me here.
  </p>
  <iframe src="//giphy.com/embed/asGdT7GTpANb2" width="480" height="320" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/please-construction-patient-asGdT7GTpANb2"></a></p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<div class="center">
  <div class="wrapper">
    <%= link_to image_tag("kboy.jpg", alt: "KBOY"), 'https://twitter.com/FernandezKboy' %>
  </div>
</div>

<br>

<div class="center">
  <p>
    <p> Need <a href="https://about.me/k-boy">help</a>,you can drop a message through <a href="https://about.me/k-boy">here</a>?</p>
  </p>
  <iframe src="//giphy.com/embed/asGdT7GTpANb2" width="480" height="320" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/please-construction-patient-asGdT7GTpANb2"></a></p>
</div>

app/views/static_pages/home.html.erb
<!-- <% provide(:title, "Home") %> -->
<br>
<div class="center jumbotron">
  <p>Visit my main blog site and portfolio site 👉  <a href="https://kirbyjames.herokuapp.com">Kirby James.</a></p>
  <p>for the meantime you can have a tour of my site :)</p>

    <iframe src="//giphy.com/embed/asGdT7GTpANb2" width="480" height="320" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/please-construction-patient-asGdT7GTpANb2"></a></p>
    <%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<div class="center">
<%= link_to image_tag("tatami.png", alt: "KBOY"),
            'http://rapollorap.herokuapp.com/' %>
<!-- <%= link_to image_tag("", alt: "KBOY"),
            'http://rapollorap.herokuapp.com/' %> -->

</div>

app/views/users/_formedit.html.erb
<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: @user %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_formnew.html.erb
   <%= form_for(@user, url: signup_path) do |f| %>
     <%= render 'shared/error_messages', object: @user %>

     <%= f.label :name %>
     <%= f.text_field :name, class: 'form-control' %>

     <!-- <%= f.label :name, "Last Name" %>
     <%= f.text_field :name, class: 'form-control' %> -->

     <%= f.label :email %>
     <%= f.email_field :email, class: 'form-control' %>

     <%= f.label :password %>
     <%= f.password_field :password, class: 'form-control' %>

     <%= f.label :password_confirmation, "Confirm Password" %>
     <%= f.password_field :password_confirmation, class: 'form-control' %>

     <%= f.submit yield(:button_text), class: "btn btn-primary" %>
   <% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure my friend?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:button_text, 'Save changes') %>
<h1>Edit Profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

      <%= render 'formedit' %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank" rel="noopener">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
<h1>Users</h1>

<%= will_paginate %>

<ul class="users">

  <%= render @users %>

</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'CREATE ACCOUNT') %>
<div class="center">
  <h1>Sign up</h1>
</div>
<div class="jumbotron">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <%= render 'formnew' %>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="center jumbotron">
  <!-- This shows the users email,name,created,updated,and time -->
  <!-- <%= @user.name %>, <%= @user.email %>,
  <%= @user.created_at %>, <%= @user.updated_at %>
  <%= Time.now %> -->
  <p>
    KBOY'S LOYAL USERS
  </p>
</div>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>